package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* Sunday, 16 November 2025 23:58:33 o'clock WAT
*/

public interface IBanqueRemoteOperations 
{
  void creerCompte (corbaBanque.Compte cpte);
  void verser (float mt, int code);
  void retirer (float mt, int code);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
  double conversion (float mt);
} // interface IBanqueRemoteOperations
